### ISSUE TITLE
Make me mod

### ISSUE THREAD

**Issue by ghost** [The-Coding-Academy/tca-helper-meet#12]
make me mod cuz yes

**Comment by StarTwi** [comment]
![image](https://user-images.githubusercontent.com/71965763/110780402-a927fd00-828a-11eb-9f12-a93bb9140075.png)
HAHA this thing :FalseFacePalmLaugh: Imao seeing this makes me feel more bad *procedes to vent on*

**Comment by pgamerx** [comment]
> ![image](https://user-images.githubusercontent.com/71965763/110780402-a927fd00-828a-11eb-9f12-a93bb9140075.png)
> HAHA this thing :FalseFacePalmLaugh: Imao seeing this makes me feel more bad _procedes to vent on_

![Alt Text](https://i.kym-cdn.com/entries/icons/original/000/034/623/Untitled-3.png)

**Comment by BobDotCom** [comment]
not for this thread
