### ISSUE TITLE
Some changes to the helper application 

### ISSUE THREAD

**Issue by zeffo** [The-Coding-Academy/tca-helper-meet#16]
The helper application is decent in its current form, but the practical questions asked do not encapsulate all the fields required for using discord.py/js; which is what the majority of people come to this server for.

Adding a few questions related to asynchronous programming, multithreading and knowledge of databases would be a good change to the application.

Would like to hear everyone's thoughts on this, especially the helper team.

**Comment by FalseDev** [comment]
I agree to this as well
